# Generated by Django 5.1.4 on 2025-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
