# Generated by Django 5.1.4 on 2025-01-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0004_gallerymodel_name_alter_departmentmodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='name',
        ),
    ]
