# Generated by Django 5.1.4 on 2025-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_remove_gallerymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
