# Generated by Django 5.1.4 on 2025-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_doctorsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
