# Generated by Django 5.1.4 on 2025-01-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_doctorsmodel_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitiesmodel',
            name='fac_image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities'),
        ),
    ]
