# Generated by Django 5.1.4 on 2025-01-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0010_facilitiesmodel_fac_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='secondapp.departmentmodel'),
        ),
    ]
