# Generated by Django 5.1.4 on 2025-01-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0011_alter_doctorsmodel_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('job_type', models.CharField(choices=[('all', 'All'), ('full time', 'Full time')], default='all', max_length=255)),
                ('job_workspace', models.CharField(choices=[('all', 'All'), ('in office', 'In Office')], default='all', max_length=255)),
                ('job_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('job_req', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
