# Generated by Django 5.1.4 on 2025-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0012_careersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersmodel',
            name='job_desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
