# Generated by Django 5.1.4 on 2025-01-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0014_alter_careersmodel_job_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersmodel',
            name='job_req',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
