# Generated by Django 5.1.4 on 2025-01-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0015_alter_careersmodel_job_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersmodel',
            name='job_req',
            field=models.TextField(blank=True, null=True),
        ),
    ]
